---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analytics
  labels:
    app: "data-analytics"
spec:
  containers:
    - name: data-analytics
      image: seliius27122.seli.gic.ericsson.se:8080/data-eea/init:v1.1


