---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analytics
  labels:
    app: "data-analytics"
spec:
  selector:
    matchLabels:
      app: data-analytics
  replicas: 1
  template:
    metadata:
      labels:
        app: data-analytics
    spec:
      containers:
        - name: data-analytics
          image: 192.168.1.2:8080/data-eea/py3.6base:v1
          readinessProbe:
            exec:
              command:
                - ls
            initialDelaySeconds: 5
            periodSeconds: 5


